#!/usr/bin/python2.7

#############################################################################################
#Change the filtered maf file generated by R and output as a snp cll type file
#############################################################################################

import sys
import os
import csv

#set up script
os.chdir('/Users/d.brown6/Documents/eQTL/Matrix_eQTL_R/')
inFile = sys.argv[1]
outFile = sys.argv[2]
data = []

#read in the files
f = open(inFile, 'U')
files = csv.reader(f, delimiter='\t')
for row in files:
    data.append(row)
    
#get the header row then remove it from data
dataHeader = data[0][:]
data = data[1:]

#create a list of patient IDs
def makeListFromColumn(table, columnNumber):
    'Do a function thing'    
    extractedList = []
    for row in table:
        extractedList.append(row[columnNumber])
    extractedListDedup = sorted(set(extractedList))
    return extractedListDedup

tumourSampleBarcode = makeListFromColumn(data, 2)
geneExtractedList = makeListFromColumn(data, 0)


