#!/usr/bin/python2.7

#############################################################################################
#Change the filtered maf file generated by R and output as a snp call type file
#############################################################################################

import sys
import os
import csv
import itertools

#set up script
os.chdir('/Users/d.brown6/Documents/FredCSC/reformattedFiles/preranked')
inFile = sys.argv[1]
data = []

#read in the files
f = open(inFile, 'U')
files = csv.reader(f, delimiter='\t')
for row in files:
    data.append(row)
    
#get the header row then remove it from data
dataHeader = data[0][:]
data = data[1:]

#sort the data
dataSort = sorted(data)




#result =[]
#for i, j in x:
#    if i[0] == j[0]:
#        if i[1] > j[1]:
#            result.append(i[0])
#            result.append(i[1])
#        else:
#            result.append(i[0])
#            result.append(j[1])
#    else:
#        result.append(j[0])
#        result.append(j[1])